from sqlalchemy import Column, String, BigInteger, Integer,\
    DateTime, Numeric, Table, UniqueConstraint
from models import Base


activeleads = Table('LMS_ACTIVELEADS', Base.metadata,
                    Column('lead_seqid', BigInteger, primary_key=True),
                    Column('lead_name', String(256)),
                    Column('lead_source_type', Integer),
                    Column('lead_source_id', BigInteger),
                    Column('lead_campaign_code', String(32)),
                    Column('createtime', DateTime),
                    Column('updatetime', DateTime),
                    Column('endtime', DateTime),
                    Column('lead_details', String(1024)),
                    Column('lead_status', Integer),
                    Column('lead_size_of_opportunity', Numeric(19, 2)),
                    Column('lead_decision_level', String(32)),
                    Column('lead_timeframe', String(19)),
                    Column('lead_wants_to_be_contacted', Integer),
                    Column('lead_competitors', String(256)),
                    Column('lead_import_userid', String(32)),
                    Column('offer_product_code', String(32)),
                    Column('offer_product_name', String(256)),
                    Column('offer_resolution_code', String(32)),
                    Column('offer_resolution_name', String(32)),
                    Column('unica_campaigncode', String(64)),
                    Column('unica_campaignname', String(64)),
                    Column('unica_treatmentcode', String(12)),
                    Column('unica_folder1', String(32)),
                    Column('unica_folder2', String(32)),
                    Column('unica_folder3', String(32)),
                    Column('mdb_customertype', Integer),
                    Column('mdb_customerid', BigInteger),
                    Column('mdb_mobilephone', String(30)),
                    Column('mdb_name', String(32)),
                    Column('mdb_birthdate', String(10)),
                    Column('mdb_sex', String(1)),
                    Column('mdb_certtype', String(3)),
                    Column('mdb_certno', String(50)),
                    Column('mdb_province', String(6)),
                    Column('mdb_provincename', String(32)),
                    Column('mdb_city', String(6)),
                    Column('mdb_cityname', String(32)),
                    Column('mdb_county', String(6)),
                    Column('mdb_countyname', String(32)),
                    Column('mdb_streetname', String(40)),
                    Column('mdb_marriagestatus', String(2)),
                    Column('mdb_childnum', String(2)),
                    Column('mdb_description', String(1024)),
                    Column('mdb_companycode', String(10)),
                    Column('mdb_ssocode', String(10)),
                    Column('mdb_channel', Integer),
                    Column('mdb_agent_code', String(12)),
                    Column('mdb_ecifid', String(12)),
                    Column('customer_json', String(2048)),
                    Column('family_json', String(2048)),
                    UniqueConstraint('lead_source_type', 'lead_source_id',
                                     'lead_campaign_code',
                                     name='idx_lms_activeleads_unique')
                    )

activeleads_mapping = mapping = {
    'createTime': 'createtime',
    'updateTime': 'updatetime',
    'endTime': 'endtime',
    'seqId': 'lead_seqid',
    'name': 'lead_name',
    'status': 'lead_status',
    'sizeOfOpportunity': 'lead_size_of_opportunity',
    'sourceType': 'lead_source_type',
    'sourceId': 'lead_source_id',
    'details': 'lead_details',
    'decisionLevel': 'lead_decision_level',
    'timeFrame': 'lead_timeFrame',
    'wantsContacted': 'lead_wants_to_be_contacted',
    'competitors': 'lead_competitors',
    'productCode': 'offer_product_code',
    'productName': 'offer_product_name',
    'resolutionCode': 'offer_resolution_code',
    'resolutionNme': 'offer_resolution_name',
    'campaignCode': 'unica_campaigncode',
    'campaignName': 'unica_campaignname',
    'treatmentCode': 'unica_treatmentcode',
    'leadCampaignCode': 'lead_campaign_code',
    'agentCode': 'mdb_agent_code',
    'ssoCode': 'mdb_ssocode',
    'companyCode': 'mdb_companycode',
    'channel': 'mdb_channel',
    'folder1': 'unica_folder1',
    'folder2': 'unica_folder2',
    'folder3': 'unica_folder3',
    'custType': 'mdb_customertype',
    'customerId': 'mdb_customerid',
    'customerName': 'mdb_name',
    'sex': 'mdb_sex',
    'birthDate': 'mdb_birthdate',
    'certType': 'mdb_certtype',
    'certNo': 'mdb_certno',
    'mobilePhone': 'mdb_mobilephone',
    'marriageStatus': 'mdb_marriagestatus',
    'childNum': 'mdb_childnum',
    'province': 'mdb_province',
    'provinceName': 'mdb_provincename',
    'city': 'mdb_city',
    'cityName': 'mdb_cityname',
    'county': 'mdb_county',
    'countyName': 'mdb_countyname',
    'streetName': 'mdb_streetname',
    'description': 'mdb_description'
}
