 CREATE VIEW raw_leads_view AS
 SELECT rl.id,
    rl.name,
    rl.budget,
    rl.need,
    rl.authority,
    rl.time_frame,
    rl.premiun,
    rl.last_modifed,
    rl.contact_id,
    rl.channel_id,
    rl.campaign_id,
    rl.company_id,
    rl.product_id,
    rc.en_name,
    rc.first_name,
    rc.last_name,
    rc.full_name,
    rc.id_type,
    rc.id_number,
    rc.gender,
    rc.age,
    rc.birth_year,
    rc.birth_month,
    rc.birth_day,
    rc.marriage,
    rc.num_of_childs,
    rc.education,
    rc.income,
    rc.job_title,
    rc.vip_flag,
    rc.mobile_phone,
    rc.home_phone,
    rc.work_phone,
    rc.email,
    rc.qq,
    rc.weixin,
    rc.open_id,
    rc.ip_address,
    rc.province_code,
    rc.city_code,
    rc.district_code,
    rc.address,
    sc.code AS saleschannel_code,
    sc.name AS saleschannel_name,
    ca.code AS campaign_code,
    ca.name AS campaign_name,
    co.code AS campany_code,
    co.name AS campany_name,
    pr.code AS product_code,
    pr.name AS product_name
   FROM (((((lms_raw_leads rl
     LEFT JOIN lms_raw_contacts rc ON ((rl.contact_id = rc.id)))
     LEFT JOIN lms_sales_channels sc ON ((rl.channel_id = sc.id)))
     LEFT JOIN lms_campaigns ca ON ((rl.campaign_id = ca.id)))
     LEFT JOIN lms_companies co ON ((rl.company_id = co.id)))
     LEFT JOIN lms_products pr ON ((rl.product_id = pr.id)))