"""init3db

Revision ID: 24638f0860db
Revises: c9c3010fff64
Create Date: 2018-11-09 08:40:18.372200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24638f0860db'
down_revision = 'c9c3010fff64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wx_accounts', sa.Column('effective_time', sa.BigInteger(), nullable=True))
    op.drop_constraint('wx_users_group_id_fkey', 'wx_users', type_='foreignkey')
    op.drop_column('wx_users', 'group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wx_users', sa.Column('group_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('wx_users_group_id_fkey', 'wx_users', 'wx_user_groups', ['group_id'], ['id'], ondelete='SET NULL')
    op.drop_column('wx_accounts', 'effective_time')
    # ### end Alembic commands ###
