"""init7db

Revision ID: 2a3361b3acd3
Revises: 327a20b49948
Create Date: 2018-11-12 19:12:00.136911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3361b3acd3'
down_revision = '327a20b49948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_page_snippets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('Title', 'Content', 'Image', 'Images', 'Separate', 'ChapterNo', 'StartTag', 'EndTag', name='snippettype'), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_page_tags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_categories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['cms_users.id'], ondelete='set null'),
    sa.ForeignKeyConstraint(['parent_id'], ['cms_categories.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_pages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('digest', sa.String(length=256), nullable=True),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('show_cover_pic', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('Create', 'Editing', 'Published', 'Removed', name='pagestatus'), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('is_public', sa.Integer(), nullable=True),
    sa.Column('pubdate', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['cms_categories.id'], ondelete='set null'),
    sa.ForeignKeyConstraint(['owner_id'], ['cms_users.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_page_tag_map',
    sa.Column('page_id', sa.BigInteger(), nullable=True),
    sa.Column('tag_id', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['cms_pages.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['cms_page_tags.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cms_page_tag_map')
    op.drop_table('cms_pages')
    op.drop_table('cms_categories')
    op.drop_table('cms_page_tags')
    op.drop_table('cms_page_snippets')
    # ### end Alembic commands ###
