"""init6db

Revision ID: 327a20b49948
Revises: 559b414d9ddc
Create Date: 2018-11-12 18:25:19.767077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327a20b49948'
down_revision = '559b414d9ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
