"""init4db

Revision ID: 559b414d9ddc
Revises: a3c062c14924
Create Date: 2018-11-09 12:31:34.749765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559b414d9ddc'
down_revision = 'a3c062c14924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cms_folders_code_key', 'cms_folders', type_='unique')
    op.drop_constraint('cms_folders_name_key', 'cms_folders', type_='unique')
    op.alter_column('wx_medias', 'author',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('wx_medias', 'name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wx_medias', 'name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('wx_medias', 'author',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.create_unique_constraint('cms_folders_name_key', 'cms_folders', ['name'])
    op.create_unique_constraint('cms_folders_code_key', 'cms_folders', ['code'])
    # ### end Alembic commands ###
