"""initdb

Revision ID: c45c0eaef654
Revises: 
Create Date: 2018-11-08 14:34:49.652577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c45c0eaef654'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AMS_AMSCSO',
    sa.Column('comCode', sa.String(length=32), nullable=False),
    sa.Column('comName', sa.String(length=32), nullable=True),
    sa.Column('comShortName', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('zipCode', sa.String(length=10), nullable=True),
    sa.Column('fax', sa.String(length=16), nullable=True),
    sa.Column('proviceNo', sa.String(length=32), nullable=True),
    sa.Column('cityNo', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=225), nullable=True),
    sa.Column('datime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('comCode')
    )
    op.create_table('AMS_AMSSALES',
    sa.Column('staffNo', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('sex', sa.String(length=4), nullable=True),
    sa.Column('birthday', sa.String(length=16), nullable=True),
    sa.Column('idno', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=225), nullable=True),
    sa.Column('channel', sa.String(length=8), nullable=True),
    sa.Column('comCode', sa.String(length=8), nullable=True),
    sa.Column('ssoCode', sa.String(length=8), nullable=True),
    sa.Column('dutyDeg', sa.String(length=8), nullable=True),
    sa.Column('dutyName', sa.String(length=64), nullable=True),
    sa.Column('joinDate', sa.BigInteger(), nullable=True),
    sa.Column('agStatus', sa.Integer(), nullable=True),
    sa.Column('startMthnum', sa.Integer(), nullable=True),
    sa.Column('quafNo', sa.String(length=32), nullable=True),
    sa.Column('quafStartDate', sa.BigInteger(), nullable=True),
    sa.Column('quafEndDate', sa.BigInteger(), nullable=True),
    sa.Column('abossnum', sa.String(length=32), nullable=True),
    sa.Column('bbossnum', sa.String(length=32), nullable=True),
    sa.Column('cbossnum', sa.String(length=32), nullable=True),
    sa.Column('dbossnum', sa.String(length=32), nullable=True),
    sa.Column('ibossnum', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('staffNo')
    )
    op.create_index('idx_amssales_comcode', 'AMS_AMSSALES', ['comCode'], unique=False)
    op.create_index('idx_amssales_ssocode', 'AMS_AMSSALES', ['ssoCode'], unique=False)
    op.create_table('AMS_AMSSSO',
    sa.Column('ssoCode', sa.String(length=32), nullable=False),
    sa.Column('ssoName', sa.String(length=225), nullable=True),
    sa.Column('comCode', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('ssoCode')
    )
    op.create_index('idx_amssso_comcode', 'AMS_AMSSSO', ['comCode'], unique=False)
    op.create_table('LMS_ACTIVELEADS',
    sa.Column('lead_seqid', sa.BigInteger(), nullable=False),
    sa.Column('lead_name', sa.String(length=256), nullable=True),
    sa.Column('lead_source_type', sa.Integer(), nullable=True),
    sa.Column('lead_source_id', sa.BigInteger(), nullable=True),
    sa.Column('lead_campaign_code', sa.String(length=32), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('endtime', sa.DateTime(), nullable=True),
    sa.Column('lead_details', sa.String(length=1024), nullable=True),
    sa.Column('lead_status', sa.Integer(), nullable=True),
    sa.Column('lead_size_of_opportunity', sa.Numeric(precision=19, scale=2), nullable=True),
    sa.Column('lead_decision_level', sa.String(length=32), nullable=True),
    sa.Column('lead_timeframe', sa.String(length=19), nullable=True),
    sa.Column('lead_wants_to_be_contacted', sa.Integer(), nullable=True),
    sa.Column('lead_competitors', sa.String(length=256), nullable=True),
    sa.Column('lead_import_userid', sa.String(length=32), nullable=True),
    sa.Column('offer_product_code', sa.String(length=32), nullable=True),
    sa.Column('offer_product_name', sa.String(length=256), nullable=True),
    sa.Column('offer_resolution_code', sa.String(length=32), nullable=True),
    sa.Column('offer_resolution_name', sa.String(length=32), nullable=True),
    sa.Column('unica_campaigncode', sa.String(length=64), nullable=True),
    sa.Column('unica_campaignname', sa.String(length=64), nullable=True),
    sa.Column('unica_treatmentcode', sa.String(length=12), nullable=True),
    sa.Column('unica_folder1', sa.String(length=32), nullable=True),
    sa.Column('unica_folder2', sa.String(length=32), nullable=True),
    sa.Column('unica_folder3', sa.String(length=32), nullable=True),
    sa.Column('mdb_customertype', sa.Integer(), nullable=True),
    sa.Column('mdb_customerid', sa.BigInteger(), nullable=True),
    sa.Column('mdb_mobilephone', sa.String(length=30), nullable=True),
    sa.Column('mdb_name', sa.String(length=32), nullable=True),
    sa.Column('mdb_birthdate', sa.String(length=10), nullable=True),
    sa.Column('mdb_sex', sa.String(length=1), nullable=True),
    sa.Column('mdb_certtype', sa.String(length=3), nullable=True),
    sa.Column('mdb_certno', sa.String(length=50), nullable=True),
    sa.Column('mdb_province', sa.String(length=6), nullable=True),
    sa.Column('mdb_provincename', sa.String(length=32), nullable=True),
    sa.Column('mdb_city', sa.String(length=6), nullable=True),
    sa.Column('mdb_cityname', sa.String(length=32), nullable=True),
    sa.Column('mdb_county', sa.String(length=6), nullable=True),
    sa.Column('mdb_countyname', sa.String(length=32), nullable=True),
    sa.Column('mdb_streetname', sa.String(length=40), nullable=True),
    sa.Column('mdb_marriagestatus', sa.String(length=2), nullable=True),
    sa.Column('mdb_childnum', sa.String(length=2), nullable=True),
    sa.Column('mdb_description', sa.String(length=1024), nullable=True),
    sa.Column('mdb_companycode', sa.String(length=10), nullable=True),
    sa.Column('mdb_ssocode', sa.String(length=10), nullable=True),
    sa.Column('mdb_channel', sa.Integer(), nullable=True),
    sa.Column('mdb_agent_code', sa.String(length=12), nullable=True),
    sa.Column('mdb_ecifid', sa.String(length=12), nullable=True),
    sa.Column('customer_json', sa.String(length=2048), nullable=True),
    sa.Column('family_json', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('lead_seqid'),
    sa.UniqueConstraint('lead_source_type', 'lead_source_id', 'lead_campaign_code', name='idx_lms_activeleads_unique')
    )
    op.create_table('LMS_ASSIGNMENT',
    sa.Column('seqId', sa.BigInteger(), nullable=False),
    sa.Column('lead_seqId', sa.BigInteger(), nullable=True),
    sa.Column('mdb_companyCode', sa.String(length=10), nullable=True),
    sa.Column('mdb_ssoCode', sa.String(length=10), nullable=True),
    sa.Column('mdb_channel', sa.Integer(), nullable=True),
    sa.Column('mdb_agent_code', sa.String(length=50), nullable=True),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('updateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('seqId')
    )
    op.create_table('LMS_TRACEACTION',
    sa.Column('seqId', sa.BigInteger(), nullable=False),
    sa.Column('lead_seqId', sa.BigInteger(), nullable=True),
    sa.Column('actionCode', sa.String(length=32), nullable=True),
    sa.Column('actionType', sa.Integer(), nullable=True),
    sa.Column('actionName', sa.String(length=32), nullable=True),
    sa.Column('actionStartTime', sa.DateTime(), nullable=True),
    sa.Column('actionEndTime', sa.DateTime(), nullable=True),
    sa.Column('actionExecTime', sa.DateTime(), nullable=True),
    sa.Column('actionResult', sa.String(length=32), nullable=True),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('updateime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('seqId')
    )
    op.create_table('LMS_TRACEPOLICY',
    sa.Column('seqId', sa.BigInteger(), nullable=True),
    sa.Column('lead_seqId', sa.BigInteger(), nullable=True),
    sa.Column('policyNo', sa.String(length=50), nullable=True),
    sa.Column('premium', sa.Float(), nullable=True),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('updateTime', sa.DateTime(), nullable=True)
    )
    op.create_table('cms_constants',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('const_type', sa.String(length=32), nullable=False),
    sa.Column('const_type_label', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('const_alias', sa.String(length=100), nullable=True),
    sa.Column('order_no', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code', 'const_type')
    )
    op.create_table('cms_departments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_images',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('img_height', sa.Integer(), nullable=True),
    sa.Column('img_width', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('default_alt_text', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_job_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('params', sa.String(length=256), nullable=True),
    sa.Column('begin_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('page_offset', sa.Integer(), nullable=True),
    sa.Column('page_limit', sa.Integer(), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=True),
    sa.Column('insert_count', sa.Integer(), nullable=True),
    sa.Column('update_count', sa.Integer(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=1024), nullable=True),
    sa.Column('result', sa.Enum('Success', 'PartialSucess', 'Fail', name='jobresult'), nullable=True),
    sa.Column('run_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_joblogs_name', 'cms_job_logs', ['name'], unique=False)
    op.create_table('cms_locations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('type', sa.Enum('Country', 'Province', 'City', 'District', name='locationtype'), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['cms_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_menus',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('icon', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('url_params', sa.String(length=128), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('order_no', sa.Integer(), nullable=True),
    sa.Column('permissions', sa.String(length=512), nullable=True),
    sa.Column('memo', sa.String(length=512), nullable=True),
    sa.Column('target', sa.String(length=20), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['cms_menus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('cms_roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('authority', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authority')
    )
    op.create_table('lms_campaigns',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lms_companies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=32), nullable=True),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('memo', sa.String(length=512), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lms_contact_company',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=32), nullable=True),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('memo', sa.String(length=512), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lms_products',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('prod_category', sa.String(length=100), nullable=True),
    sa.Column('memo', sa.String(length=512), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lms_sales_channels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('memo', sa.String(length=512), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lms_transform_rules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('dir', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wx_accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('app_id', sa.String(length=16), nullable=False),
    sa.Column('app_secret', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('access_token', sa.String(length=64), nullable=True),
    sa.Column('refresh_time', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Locked', 'Removed', name='accountstatus'), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_organizations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('short_name', sa.String(length=64), nullable=True),
    sa.Column('org_type', sa.Enum('GroupCompany', 'Company', 'Branch', 'Department', name='orgtype'), nullable=True),
    sa.Column('telephone', sa.String(length=32), nullable=True),
    sa.Column('mobilephone', sa.String(length=32), nullable=True),
    sa.Column('fax', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('province', sa.String(length=32), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('postcode', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('memo', sa.String(length=512), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.Column('org_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Locked', 'Removed', name='orgstatus'), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['cms_locations.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['cms_organizations.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_role_menu',
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('menu_id', sa.BigInteger(), nullable=True),
    sa.Column('permissions', sa.String(length=512), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['cms_menus.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['cms_roles.id'], )
    )
    op.create_table('lms_import_templates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('template_file', sa.String(length=100), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('clean_rule_id', sa.BigInteger(), nullable=True),
    sa.Column('merge_rule_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['lms_sales_channels.id'], ),
    sa.ForeignKeyConstraint(['clean_rule_id'], ['lms_transform_rules.id'], ),
    sa.ForeignKeyConstraint(['merge_rule_id'], ['lms_transform_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wx_medias',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('media_id', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('type', sa.Enum('IMAGE', 'VIDEO', 'VOICE', 'NEWS', name='mediatype'), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('thumb_media_id', sa.BigInteger(), nullable=True),
    sa.Column('show_cover_pic', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=32), nullable=True),
    sa.Column('digest', sa.String(length=256), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_source_url', sa.String(length=1024), nullable=True),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['wx_accounts.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wx_user_groups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['wx_accounts.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wx_user_tags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['wx_accounts.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=128), nullable=True),
    sa.Column('enname', sa.String(length=128), nullable=True),
    sa.Column('fullname', sa.String(length=128), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('salt', sa.String(length=64), nullable=True),
    sa.Column('employee_no', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Locked', 'Removed', name='userstatus'), nullable=True),
    sa.Column('usertype', sa.Enum('SysAdmin', 'Admin', 'Sales', name='usertype'), nullable=True),
    sa.Column('organization_id', sa.BigInteger(), nullable=True),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('account_expired', sa.Boolean(), nullable=True),
    sa.Column('account_locked', sa.Boolean(), nullable=True),
    sa.Column('password_expired', sa.Boolean(), nullable=True),
    sa.Column('password_errors', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['cms_organizations.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('username')
    )
    op.create_table('wx_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=False),
    sa.Column('unionid', sa.String(length=64), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('province', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('headimgurl', sa.String(length=512), nullable=True),
    sa.Column('remark', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('tags', sa.String(length=256), nullable=True),
    sa.Column('subscribe', sa.Integer(), nullable=True),
    sa.Column('subscribe_time', sa.BigInteger(), nullable=True),
    sa.Column('subscribe_scene', sa.String(length=32), nullable=True),
    sa.Column('qr_scene', sa.Integer(), nullable=True),
    sa.Column('qr_scene_str', sa.String(length=256), nullable=True),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['wx_accounts.id'], ondelete='set null'),
    sa.ForeignKeyConstraint(['group_id'], ['wx_user_groups.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_folders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['cms_users.id'], ondelete='set null'),
    sa.ForeignKeyConstraint(['parent_id'], ['cms_folders.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cms_operation_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('detail', sa.String(length=4000), nullable=True),
    sa.Column('object_id', sa.BigInteger(), nullable=True),
    sa.Column('object', sa.String(length=128), nullable=True),
    sa.Column('type', sa.Enum('Login', 'Logout', 'Create', 'Update', 'Delete', 'Import', 'Upload', 'Download', name='opertype'), nullable=True),
    sa.Column('result', sa.Enum('Success', 'PartialSucess', 'Fail', name='operresult'), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['cms_users.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_user_auth_memberships',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('provider_userid', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['cms_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_user_preferences',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('language', sa.String(length=30), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('memo', sa.String(length=512), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['cms_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_user_role',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['cms_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['cms_users.id'], )
    )
    op.create_table('cms_user_tokens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.Enum('API', 'FEEDS', 'RECOVERY', 'AUTOLOGIN', name='tokenaction'), nullable=True),
    sa.Column('value', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['cms_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lms_collections',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.Enum('ImportCSV', 'ImportDB', 'ImportXML', 'CronImport', name='collectiontype'), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('save_file', sa.String(length=100), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=True),
    sa.Column('fail_count', sa.Integer(), nullable=True),
    sa.Column('collect_count', sa.Integer(), nullable=True),
    sa.Column('viable_count', sa.Integer(), nullable=True),
    sa.Column('merge_count', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('template_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('cost_time', sa.BigInteger(), nullable=True),
    sa.Column('error_code', sa.String(length=10), nullable=True),
    sa.Column('error_msg', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('Collecting', 'Fail', 'Success', 'Cleaned', 'Merged', name='collectionstatus'), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['lms_sales_channels.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['lms_import_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['cms_users.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_files',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('type', sa.Enum('IMAGE', 'VIDEO', 'VOICE', 'TXT', 'CSV', 'EXCEL', 'WORD', 'PPT', 'PDF', name='filetype'), nullable=True),
    sa.Column('folder_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('is_public', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['cms_folders.id'], ondelete='set null'),
    sa.ForeignKeyConstraint(['owner_id'], ['cms_users.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_monitor_charts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('collect_count', sa.Integer(), nullable=True),
    sa.Column('viable_count', sa.Integer(), nullable=True),
    sa.Column('merge_count', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('collection_id', sa.BigInteger(), nullable=True),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('begin_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('Open', 'Closed', name='monitorstatus'), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['lms_campaigns.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['lms_sales_channels.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['lms_collections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['cms_users.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lms_raw_contacts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('no', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.BigInteger(), nullable=True),
    sa.Column('en_name', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('birth_date', sa.String(length=20), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('birth_month', sa.Integer(), nullable=True),
    sa.Column('birth_day', sa.Integer(), nullable=True),
    sa.Column('id_type', sa.Integer(), nullable=True),
    sa.Column('id_number', sa.String(length=50), nullable=True),
    sa.Column('marriage', sa.Integer(), nullable=True),
    sa.Column('num_of_childs', sa.Integer(), nullable=True),
    sa.Column('education', sa.Integer(), nullable=True),
    sa.Column('income', sa.Integer(), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('vip_flag', sa.String(length=100), nullable=True),
    sa.Column('mobile_phone', sa.String(length=20), nullable=True),
    sa.Column('home_phone', sa.String(length=20), nullable=True),
    sa.Column('work_phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('qq', sa.String(length=20), nullable=True),
    sa.Column('weixin', sa.String(length=50), nullable=True),
    sa.Column('open_id', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('country_name', sa.String(length=64), nullable=True),
    sa.Column('province_code', sa.String(length=10), nullable=True),
    sa.Column('province_name', sa.String(length=50), nullable=True),
    sa.Column('city_code', sa.String(length=10), nullable=True),
    sa.Column('city_name', sa.String(length=50), nullable=True),
    sa.Column('district_code', sa.String(length=10), nullable=True),
    sa.Column('district_name', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['lms_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lms_transform_tasks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('collection_id', sa.BigInteger(), nullable=True),
    sa.Column('template_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('Created', 'Cleaning', 'CleanSuccess', 'CleanFail', 'Merging', 'MergeSuccess', 'MergeFail', name='transformtaskstatus'), nullable=True),
    sa.Column('error_msg', sa.String(length=1024), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['lms_collections.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['lms_import_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lms_viable_contacts',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('no', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.BigInteger(), nullable=True),
    sa.Column('en_name', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('birth_date', sa.String(length=20), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('birth_month', sa.Integer(), nullable=True),
    sa.Column('birth_day', sa.Integer(), nullable=True),
    sa.Column('id_type', sa.Integer(), nullable=True),
    sa.Column('id_number', sa.String(length=50), nullable=True),
    sa.Column('marriage', sa.Integer(), nullable=True),
    sa.Column('num_of_childs', sa.Integer(), nullable=True),
    sa.Column('education', sa.Integer(), nullable=True),
    sa.Column('income', sa.Integer(), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('vip_flag', sa.String(length=100), nullable=True),
    sa.Column('mobile_phone', sa.String(length=20), nullable=True),
    sa.Column('home_phone', sa.String(length=20), nullable=True),
    sa.Column('work_phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('qq', sa.String(length=20), nullable=True),
    sa.Column('weixin', sa.String(length=50), nullable=True),
    sa.Column('open_id', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('country_name', sa.String(length=64), nullable=True),
    sa.Column('province_code', sa.String(length=10), nullable=True),
    sa.Column('province_name', sa.String(length=50), nullable=True),
    sa.Column('city_code', sa.String(length=10), nullable=True),
    sa.Column('city_name', sa.String(length=50), nullable=True),
    sa.Column('district_code', sa.String(length=10), nullable=True),
    sa.Column('district_name', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['lms_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lms_raw_leads',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('no', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('need', sa.String(length=100), nullable=True),
    sa.Column('authority', sa.String(length=100), nullable=True),
    sa.Column('time_frame', sa.String(length=100), nullable=True),
    sa.Column('premiun', sa.Integer(), nullable=True),
    sa.Column('effective', sa.Integer(), nullable=True),
    sa.Column('merge_status', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('contact_id', sa.BigInteger(), nullable=True),
    sa.Column('collection_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('customer_type', sa.Integer(), nullable=True),
    sa.Column('customer_json', sa.String(length=2048), nullable=True),
    sa.Column('family_json', sa.String(length=2048), nullable=True),
    sa.Column('agentcode', sa.String(length=50), nullable=True),
    sa.Column('err_msg', sa.String(length=4000), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['lms_campaigns.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['lms_sales_channels.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['lms_collections.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['lms_companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['lms_raw_contacts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['lms_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lms_rawleads_created_date', 'lms_raw_leads', ['created_date'], unique=False)
    op.create_table('lms_viable_leads',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('no', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('need', sa.String(length=100), nullable=True),
    sa.Column('authority', sa.String(length=100), nullable=True),
    sa.Column('time_frame', sa.String(length=100), nullable=True),
    sa.Column('premiun', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('contact_id', sa.BigInteger(), nullable=True),
    sa.Column('collection_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('customer_type', sa.Integer(), nullable=True),
    sa.Column('customer_json', sa.String(length=2048), nullable=True),
    sa.Column('family_json', sa.String(length=2048), nullable=True),
    sa.Column('agentcode', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modifed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['lms_campaigns.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['lms_sales_channels.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['lms_collections.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['lms_companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['lms_viable_contacts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['lms_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lms_viableleads_created_date', 'lms_viable_leads', ['created_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_lms_viableleads_created_date', table_name='lms_viable_leads')
    op.drop_table('lms_viable_leads')
    op.drop_index('idx_lms_rawleads_created_date', table_name='lms_raw_leads')
    op.drop_table('lms_raw_leads')
    op.drop_table('lms_viable_contacts')
    op.drop_table('lms_transform_tasks')
    op.drop_table('lms_raw_contacts')
    op.drop_table('cms_monitor_charts')
    op.drop_table('cms_files')
    op.drop_table('lms_collections')
    op.drop_table('cms_user_tokens')
    op.drop_table('cms_user_role')
    op.drop_table('cms_user_preferences')
    op.drop_table('cms_user_auth_memberships')
    op.drop_table('cms_operation_logs')
    op.drop_table('cms_folders')
    op.drop_table('wx_users')
    op.drop_table('cms_users')
    op.drop_table('wx_user_tags')
    op.drop_table('wx_user_groups')
    op.drop_table('wx_medias')
    op.drop_table('lms_import_templates')
    op.drop_table('cms_role_menu')
    op.drop_table('cms_organizations')
    op.drop_table('wx_accounts')
    op.drop_table('lms_transform_rules')
    op.drop_table('lms_sales_channels')
    op.drop_table('lms_products')
    op.drop_table('lms_contact_company')
    op.drop_table('lms_companies')
    op.drop_table('lms_campaigns')
    op.drop_table('cms_roles')
    op.drop_table('cms_menus')
    op.drop_table('cms_locations')
    op.drop_index('idx_joblogs_name', table_name='cms_job_logs')
    op.drop_table('cms_job_logs')
    op.drop_table('cms_images')
    op.drop_table('cms_departments')
    op.drop_table('cms_constants')
    op.drop_table('LMS_TRACEPOLICY')
    op.drop_table('LMS_TRACEACTION')
    op.drop_table('LMS_ASSIGNMENT')
    op.drop_table('LMS_ACTIVELEADS')
    op.drop_index('idx_amssso_comcode', table_name='AMS_AMSSSO')
    op.drop_table('AMS_AMSSSO')
    op.drop_index('idx_amssales_ssocode', table_name='AMS_AMSSALES')
    op.drop_index('idx_amssales_comcode', table_name='AMS_AMSSALES')
    op.drop_table('AMS_AMSSALES')
    op.drop_table('AMS_AMSCSO')
    # ### end Alembic commands ###
