"""init3db

Revision ID: cc15197c2dfc
Revises: 24638f0860db
Create Date: 2018-11-09 10:37:52.935792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc15197c2dfc'
down_revision = '24638f0860db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wx_medias', sa.Column('update_time', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wx_medias', 'update_time')
    # ### end Alembic commands ###
