from sqlalchemy import Column, String, Table, DateTime,\
    BigInteger, Integer, Numeric
from models import Base


customertag = Table('CUSTOMERTAG', Base.metadata,
                    Column('customerID', BigInteger),
                    Column('sex', String(1)),
                    Column('age', String(3)),
                    Column('birthDate', String(20)),
                    Column('constellation', String(10)),
                    Column('idType', String(3)),
                    Column('nationality', String(10)),
                    Column('ageGroup', String(10)),
                    Column('customerChannel', String(1)),
                    Column('customerGroup', String(2)),
                    Column('leadTime', Integer),
                    Column('hotLeadsTime', Integer),
                    Column('customerLevel', String(2)),
                    Column('lifeStage', String(1)),
                    Column('familyStage', String(1)),
                    Column('mobileFlag', String(1)),
                    Column('emailFlag', String(1)),
                    Column('addressFlag', String(1)),
                    Column('addressNo', String(6)),
                    Column('provinceNo', String(6)),
                    Column('cityNo', String(6)),
                    Column('countyNo', String(6)),
                    Column('occupationStatus', String(1)),
                    Column('educateLevel', String(2)),
                    Column('marriageStatus', String(2)),
                    Column('childNum', Integer),
                    Column('childAge', Integer),
                    Column('child2Age', Integer),
                    Column('familySalar', Numeric(16, 2)),
                    Column('socialInsuFlag', String(1)),
                    Column('licenseType', String(2)),
                    Column('healthCondition', String(5)),
                    Column('smokeFlag', String(1)),
                    Column('mobileType', String(32)),
                    Column('mobileModel', String(50)),
                    Column('fontSize', String(10)),
                    Column('officeWorkFlag', String(1)),
                    Column('saleNumber', Numeric(3)),
                    Column('yearPremium', Numeric(16, 2)),
                    Column('policyNumber', Integer),
                    Column('firstAPPDate', DateTime),
                    Column('firstAPPChannel', String(1)),
                    Column('firstProductCode', String(50)),
                    Column('firstSalesNo', String(12)),
                    Column('recentAPPDate1', DateTime),
                    Column('recentAPPDate2', DateTime),
                    Column('recentProductCode1', String(50)),
                    Column('recentProductCode2', String(50)),
                    Column('recentAppChannel1', String(1)),
                    Column('recentAppChannel2', String(1)),
                    Column('recentSalesNo1', String(12)),
                    Column('recentSalesNo2', String(12)),
                    Column('terminationDate1', DateTime),
                    Column('terminationDate2', DateTime),
                    Column('terminationPrdCode1', String(50)),
                    Column('terminationPrdCode2', String(50)),
                    Column('lifeFlag', String(1)),
                    Column('diseaseFlag', String(1)),
                    Column('accidentFlag', String(1)),
                    Column('medicalFlag', String(1)),
                    Column('regFlag', String(1)),
                    Column('wechatFlag', String(1)),
                    Column('assessmentFlag', String(1)),
                    Column('contactOnlineFlag', String(1)),
                    Column('familyPlicyFlag', String(1)),
                    Column('homeNumber', String(1)),
                    Column('addPolicyFlag', String(1)),
                    Column('epolicyFlag', String(1)),
                    Column('recentInterDate', DateTime),
                    Column('recentCallDate', DateTime),
                    Column('recentOnlineDate', DateTime),
                    Column('recentCounterDate', DateTime),
                    Column('endorendDate', DateTime),
                    Column('recentClaimTime', DateTime),
                    Column('policyLoanFlag', String(1)),
                    Column('returnFlag', String(1)),
                    Column('loanAmount', Numeric(16, 2)),
                    Column('loanReason', String(64)),
                    Column('loanTime', DateTime),
                    Column('repayTime', DateTime),
                    Column('deferredPayment', String(1)),
                    Column('complainFlag', String(1)),
                    Column('fraudFlag', String(1)),
                    Column('notInformFlag', String(1))
                    )
