from sqlalchemy import Column, String, Table, DateTime,BigInteger,Integer,Numeric
from models import Base


lccont = Table('LCCONT', Base.metadata,
    Column('transactionNo',String(28)),
    Column('companyCode',String(30)),
    Column('grpPolicyNo', String(50)),
    Column('policyNo', String(50)),
    Column('prtNo', String(50)),
    Column('gpFlag', String(30)),
    Column('familypPolType', String(30)),
    Column('manageCom', String(30)),
    Column('manageComName', String(100)),
    Column('circpoPedomCode', String(30)),
    Column('effPrefectureCode', String(30)),
    Column('distribChnl', String(30)),
    Column('agencyCode', String(50)),
    Column('agencyName', String(120)),
    Column('appntNo', String(50)),
    Column('customerNo', String(50)),
    Column('appntName', String(500)),
    Column('appntSex', String(30)),
    Column('appntBirthDate', DateTime),
    Column('appntCertType', String(30)),
    Column('appntCertNo', String(50)),
    Column('province', String(30)),
    Column('city', String(30)),
    Column('county', String(30)),
    Column('street', String(200)),
    Column('appntMP', String(30)),
    Column('appntFP', String(30)),
    Column('email', String(100)),
    Column('payMode', String(30)),
    Column('payWay', String(30)),
    Column('signDate', DateTime),
    Column('currency', String(30)),
    Column('copies',BigInteger),
    Column('premium',Numeric(16,2)),
    Column('sumInsured', Numeric(16,2)),
    Column('cashValue', Numeric(16,2)),
    Column('polBalance', Numeric(16,2)),
    Column('accumPremium', Numeric(16,2)),
    Column('accumLoanMoney',Numeric(16,2)),
    Column('aplMoney', Numeric(16,2)),
    Column('curPaidToDate', DateTime),
    Column('payBeginDate', DateTime),
    Column('effDate', DateTime),
    Column('uwDate', DateTime),
    Column('uwType', String(30)),
    Column('polApplyDate', DateTime),
    Column('polSignFlag', String(30)),
    Column('customGetPolDate', DateTime),
    Column('polStatus', String(30)),
    Column('bankCode', String(30)),
    Column('bankName', String(100)),
    Column('bankAccNo', String(40)),
    Column('accName', String(120)),
    Column('policyType', String(30)),
    Column('policyEndDate', DateTime),
    Column('terminationDate', DateTime),
    Column('suspendDate',DateTime),
    Column('recoverDate', DateTime),
    Column('terminationReason', String(30)),
    Column('contSendFlag', String(30)),
    Column('appntSalary', Numeric(16,2))

)
